### ISSUE TITLE
Reported by Monzy

### ISSUE THREAD

**Issue by patel-bhavin** [splunk/security-content#336]
ESCU 1.0.49, Content Library view/page, Analytics Story Details, Last updated column. 
The latest date is 2019-12-11. This doesn't seem right.

the story version should be bumped as well

**Comment by patel-bhavin** [comment]
Solution: 
1) we should update the modification date of story and search both when its updated.
2) When a detection search is updated: bump the X in story version to 1.x 
When the story itself is updated, bump the Y in story version

**Comment by patel-bhavin** [comment]
This issue will be fixed in 1.0.50

**Comment by d1vious** [comment]
closed by PR https://github.com/splunk/security-content/pull/351
