### ISSUE TITLE
Possible bug in rule: "AWS Activity In New Region"

### ISSUE THREAD

**Issue by tdziwok** [splunk/security-content#343]
Hi ESCU Team, 

I think there may have been an inadvertent bug introduced in: f9bdf7e0e45b0304838b34cd88fe9c3e5aecf847 

The rule from [detections/aws_activity_in_new_region.yml](https://github.com/splunk/security-content/blob/656b66cd7115a3c08683f9afe1fceece7faea1c0/detections/aws_activity_in_new_region.yml#L40) no longer runs in Splunk, as `| convert security_content_ctime(earliest) security_content_ctime(latest)` is not a valid usage of the `convert` command. 

I am guessing that this is an instance where `sed` or another replacing tool caught some "real" `ctime` invocations while looking for instances of the old macro name. 

Thanks, 
Tomasz

**Comment by d1vious** [comment]
It definetly looks to be the case @tdziwok, thank you for pointing this out! We will work on a PR to get it fixed up. If you did any changes to the search it would be great if you could shared it as an example fix 😄

**Comment by d1vious** [comment]
Hey added a PR to fix this https://github.com/splunk/security-content/pull/345 should be fixed in the next release.

**Comment by tdziwok** [comment]
Hi @d1vious, 

Thanks for looking into this so quickly. 
The fix you applied is exactly what I had used; sorry for not sharing it earlier :).

I believe I have found one more instance of the same issue by using: 
```bash
grep  -irE '([^`]|^)security_content_ctime' ./detections/
```
[./detections/ec2_instance_started_with_previously_unseen_instance_type.yml](https://github.com/splunk/security-content/blob/e134fb24c89ad34e34d95876fc8aa1e2206afd0c/detections/ec2_instance_started_with_previously_unseen_instance_type.yml#L41) has the same exact pattern and needs the same exact fix. 

Thanks for your help, and keep up the awesome work! 

Thanks, 
Tomasz

**Comment by d1vious** [comment]
@tdziwok thank you for sharing this one too, re-opened the issue for now. I will make another PR to solve this one.

**Comment by d1vious** [comment]
@tdziwok added another PR in there to include this search. Thank you again for catching this error!
