### ISSUE TITLE
AWS Cloud Provisioning From Previously Unseen IP Address

### ISSUE THREAD

**Issue by carroyod** [splunk/security-content#444]
Iplocation and filter events that have Country field defined has no sense for this use case:

Remove next form the rule:

| iplocation sourceIPAddress | search Country=*

**Comment by patel-bhavin** [comment]
@carroyod : Thanks for creating this issue and fixing it in a PR. We love community contributions and appreciate you taking the time.

**Comment by d1vious** [comment]
resolved in PR https://github.com/splunk/security-content/pull/445
