### ISSUE TITLE
Documentation is mentioning "developing" but does not point to anything

### ISSUE THREAD

**Issue by 160NZ413Z** [splunk/security-content#510]
Hi, documentation mentions the possibility to write content and a  "Developping" section but  https://github.com/splunk/security-content#developing leads to nothing. It would be nice to get a link on how to create its own content or create its own app to manage custom content under the same format.
Thanks !

**Comment by d1vious** [comment]
Hey @160NZ413Z great point looks like that got lost from a recent major update, you can find that section in an older version of the readme https://github.com/splunk/security-content/tree/3ab384a191e40c136770bb0edd4dca9302e8eab5#developing. Let me create a wiki page and fix that link. Will come back to you with better docs! For now a good place to start is reviewing our contributor guide: https://github.com/splunk/security-content/blob/develop/docs/CONTRIBUTING.md.

**Comment by d1vious** [comment]
Hey @160NZ413Z updated our wiki and included a [Developing Content page](https://github.com/splunk/security-content/wiki/Developing-Content). Also started a PR to fix the README https://github.com/splunk/security-content/pull/511.
