### ISSUE TITLE
Fix issue with multiple layers in ATT&CK Navigator

### ISSUE THREAD

**Issue by jkuepker** [splunk/security-content#688]
There is currently an issue where multiple layers do not work for some users. https://github.com/mitre-attack/attack-navigator/issues/199

**Comment by d1vious** [comment]
Hey @jkuepker thank you! Looks like its fixed in the upcoming release 4.0 for the navigator, will update the code once that gets merge to master! For now will keep this open.

**Comment by josehelps** [comment]
Resolved on PR #1064 Thank you again for being patient with us on this one.
