### ISSUE TITLE
"ESCU - Baseline Of Cloud Instances Destroyed" failed with "Error in 'fit' command: Error while fitting "DensityFunction" model: Unable to fit an Exponential distribution due to numerical errors. All values in the dataset are the same."

### ISSUE THREAD

**Issue by kkolli4** [splunk/security-content#692]
<img width="1542" alt="Screen Shot 2020-09-29 at 4 15 26 PM" src="https://user-images.githubusercontent.com/72111751/94628611-46f7b480-0275-11eb-9baf-f7c4ef867530.png">

**Comment by patel-bhavin** [comment]
the search is failing since there is a expon (exponential distribution)explicitly set in the fit command. Updating the search to remove that parameter

**Comment by patel-bhavin** [comment]
this issue is fixed in the following commit 

https://github.com/splunk/security-content/pull/640/commits/d95a7452f5353fa0785d365f467ba56f51284621

Thank you for reporting this bug @kkolli4

**Comment by patel-bhavin** [comment]
As discussed, reverted this commit as this parameter dist=expon is intentional
