### ISSUE TITLE
Workbench Panels are not handling tokens with multiple values correctly.

### ISSUE THREAD

**Issue by knadkarni-splunk** [splunk/security-content#697]
**Linked ES Issue:** https://jira.splunk.com/browse/SOLNESS-24192

Workbench panel 'Get Parent Process Info' and the prebuilt panel 'workbench_panel_get_parent_process_info' which it uses don't function correctly when the multiple artifacts of an ES investigation are explored. The search query in the panel 'workbench_panel_get_parent_process_info' doesn't consider that the tokens used in the query may have multiple values which may need to be 'AND'ed or 'OR'ed. Along with that, the 'Get Parent Process Info' workbench panel also needs to be modified to correctly use 'Value Prefix', 'Value Suffix' and delimiters taking multiple values for the tokens into account.

There are other workbench panels like 'Get Authentication Logs For Endpoint' and 'Get Process Information For Port Activity' which also face the same issue.

**Comment by patel-bhavin** [comment]
@knadkarni-splunk : those work bench searches are intended to work with single artifacts only. There is no easy way currently to customize those with our current tooling.

**Comment by knadkarni-splunk** [comment]
@patel-bhavin Can't the panels be designed to take multiple values for tokens into account (Using delimiters ,value prefix and value suffix)? Can this be addressed in an upcoming release?

**Comment by patel-bhavin** [comment]
@knadkarni-splunk : After doing a bunch of testing/tweaks with our current script that generates `es_investigations.conf` , it seems like we might be able to handle multiple values.

That said, it looks like a size-able amount of work as we'd have to update all the searches in the response tasks directory. Will keep you posted on when this will be ready

**Comment by patel-bhavin** [comment]
tracking this in https://github.com/splunk/security-content/pull/new/workbench_issue_697 -> no longer a correct branch

New branch: https://github.com/splunk/security-content/pull/987

**Comment by patel-bhavin** [comment]
This issue is fixed in 3.10.0. Thank you @knadkarni-splunk for creating this and giving details
