### ISSUE TITLE
Add more synthetic datasets for SSA unit testing

### ISSUE THREAD

**Issue by harsha2010** [splunk/security-content#748]
[first_time_seen_commandline.txt](https://github.com/splunk/security-content/files/5375365/first_time_seen_commandline.txt)
[unusual_commandline.txt](https://github.com/splunk/security-content/files/5375368/unusual_commandline.txt)

**Comment by josehelps** [comment]
Used to create a manual test in SMLE, committed notebooks here https://github.com/splunk/security-content/tree/develop/notebooks
